"""add user occupation and date of birth

Revision ID: 8c235859e485
Revises: b8f0fd385d21
Created: 2026-09-22 18:12:41.693329

Both columns are nullable. occupation applies to Employees only. date_of_birth
is required by the API for every user written from now on, but rows that
already exist have no true value to backfill; a later migration can make it
NOT NULL once they do.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8c235859e485'
down_revision: str | None = 'b8f0fd385d21'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'occupation')
    # ### end Alembic commands ###
