"""add notifications

Revision ID: c49f04286e46
Revises: 8c235859e485
Created: 2026-09-23 12:48:03.593167

One row per recipient per event, written in the same transaction as the
report or assignment it announces. Both foreign keys to the thing announced
cascade: a deleted incident takes its notifications with it, and so does a
deleted user. The actor is SET NULL, since the announcement reads without one.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c49f04286e46'
down_revision: str | None = '8c235859e485'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('Assigned', 'Reported', name='notificationkind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('incident_title', sa.String(length=200), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_notifications_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_notifications_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_incident_id', 'notifications', ['incident_id'], unique=False)
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_index('ix_notifications_incident_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
