"""record the assignee on history rows

Revision ID: 83edc3342052
Revises: c49f04286e46
Created: 2026-09-23 19:55:05.145524

A history row now names the engineer the event handed the incident to, so
the timeline can say which admin assigned whom. Nullable: most rows change
no hands. SET NULL like `incidents.assignee_id`, so deleting a user keeps the
audit trail. Existing rows stay null; nothing recorded who was assigned.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '83edc3342052'
down_revision: str | None = 'c49f04286e46'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_status_history', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_incident_status_history_assignee_id_users'), 'incident_status_history', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_incident_status_history_assignee_id_users'), 'incident_status_history', type_='foreignkey')
    op.drop_column('incident_status_history', 'assignee_id')
    # ### end Alembic commands ###
