"""Shared kernel for the ACME Facility Incident Management services.

This package is the single source of truth for configuration, persistence,
domain models, the incident workflow, row-level access control and the error
envelope. It is physically copied into each service directory at build time by
`tools/sync-shared.sh`, because infra/lambda.tf passes a single-element
`source_path` to the Lambda module and only one directory is ever zipped.

Edit here. Never edit `backend/<service>/acme_core/` -- that is a build artifact
and the next sync discards it.
"""

from __future__ import annotations

__version__ = "0.1.0"

__all__ = ["__version__", "build_stamp"]


def build_stamp() -> dict[str, object]:
    """Return the git provenance of this copy, for staleness diagnosis.

    `_build_stamp.py` is generated by tools/sync-shared.sh and is absent when
    running from the source tree, so the caller always gets a usable dict.

    Returns:
        A mapping with `git_sha`, `dirty` and `stamped_at` keys. When the stamp
        is missing, `git_sha` is `"source"`.
    """
    try:
        from acme_core import _build_stamp as stamp
    except ImportError:
        return {"git_sha": "source", "dirty": None, "stamped_at": None}
    return {
        "git_sha": stamp.GIT_SHA,
        "dirty": stamp.DIRTY,
        "stamped_at": stamp.STAMPED_AT,
    }
