"""The migration itself, exercised rather than inspected."""

from __future__ import annotations

import pytest
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from sqlalchemy import Connection, inspect, text

from acme_core.db.migrate import (
    current_revision,
    downgrade,
    head_revision,
    migrations_pending,
    upgrade_head,
)
from acme_core.models import EXPECTED_TABLES, Base

pytestmark = pytest.mark.integration


class TestAppliedSchema:
    def test_every_expected_table_exists(self, connection: Connection) -> None:
        names = set(inspect(connection).get_table_names())
        assert EXPECTED_TABLES <= names

    def test_alembic_stamped_at_head(self, database_url: str) -> None:
        assert current_revision(database_url) == head_revision()

    def test_nothing_pending(self, database_url: str) -> None:
        assert migrations_pending(database_url) is False


class TestNoModelDrift:
    def test_no_pending_autogenerate_diff(self, connection: Connection) -> None:
        """Catches the classic rot: a model edited without a migration.

        Compares the live schema against Base.metadata exactly as
        `alembic revision --autogenerate` would, and asserts it finds nothing.
        """
        context = MigrationContext.configure(
            connection,
            opts={"compare_type": True, "compare_server_default": True},
        )
        diff = compare_metadata(context, Base.metadata)
        assert diff == [], f"model and migration have drifted: {diff}"


class TestConstraints:
    def test_naming_convention_was_applied(self, connection: Connection) -> None:
        """An auto-named constraint cannot be reliably dropped on downgrade."""
        inspector = inspect(connection)
        pk = inspector.get_pk_constraint("users")
        assert pk["name"] == "pk_users"

    def test_enum_columns_carry_a_check(self, connection: Connection) -> None:
        count = connection.execute(
            text(
                "SELECT count(*) FROM pg_constraint c "
                "JOIN pg_class t ON t.oid = c.conrelid "
                "JOIN pg_namespace n ON n.oid = t.relnamespace "
                "WHERE n.nspname = 'public' AND c.contype = 'c'"
            )
        ).scalar_one()
        # role, status, priority, visibility, escalation status, from_status, to_status
        assert count == 7

    def test_no_naive_timestamp_columns(self, connection: Connection) -> None:
        """Mixing naive and aware timestamps makes SLA arithmetic wrong."""
        count = connection.execute(
            text(
                "SELECT count(*) FROM information_schema.columns "
                "WHERE table_schema = 'public' "
                "AND data_type = 'timestamp without time zone'"
            )
        ).scalar_one()
        assert count == 0

    def test_constraint_names_are_unique_within_each_table(
        self, connection: Connection
    ) -> None:
        """Two columns sharing an enum in one table collide on the CHECK name.

        PostgreSQL rejects the duplicate at CREATE TABLE, so this fails the
        migration outright rather than producing a subtly wrong schema.
        """
        rows = connection.execute(
            text(
                "SELECT conrelid::regclass::text AS tbl, conname, count(*) "
                "FROM pg_constraint c "
                "JOIN pg_class t ON t.oid = c.conrelid "
                "JOIN pg_namespace n ON n.oid = t.relnamespace "
                "WHERE n.nspname = 'public' "
                "GROUP BY 1, 2 HAVING count(*) > 1"
            )
        ).all()
        assert rows == []


class TestReversibility:
    def test_downgrade_then_upgrade_is_clean(self, database_url: str) -> None:
        """An autogenerated downgrade is usually the part nobody checks.

        Runs last-ish by name, and restores head before yielding, so the rest of
        the suite is unaffected.
        """
        try:
            assert downgrade("base", database_url) == ""
            assert current_revision(database_url) is None
        finally:
            upgrade_head(database_url)
        assert current_revision(database_url) == head_revision()
