#!/usr/bin/env bash
#
# Mirror backend/_shared/acme_core into every discovered Python service directory.
#
# Why this exists: infra/lambda.tf:20-25 passes a SINGLE-element source_path to the
# Lambda module, so exactly one directory is zipped. Shared code therefore has to be
# physically present inside each service directory at build time. Symlinks do not
# work -- the packager walks with os.walk(), which does not follow directory symlinks.
#
# Run via `make deploy`, never by hand. bin/deploy-backend.sh is just `terraform
# apply` and does NOT call this, so deploying without it ships a Lambda with no
# acme_core at all (the copies are gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
SRC="$ROOT/backend/_shared/acme_core"

[ -d "$SRC" ] || { echo "FATAL: $SRC does not exist" >&2; exit 1; }
command -v rsync >/dev/null || { echo "FATAL: rsync not found" >&2; exit 1; }

# Operational code that only the auth service is allowed to carry. Shipping the
# migrate/seed entrypoints to every service would mean three doors to a schema
# rewrite where one suffices.
AUTH_ONLY=(migrations seed.py admin_actions.py)

# Build stamp, so a stale deploy is one curl away from being obvious instead of an
# afternoon of confusion. Surfaced by GET /api/<service>/healthz.
GIT_SHA="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null)" ]; then DIRTY=True; else DIRTY=False; fi
STAMPED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$SRC/_build_stamp.py" <<STAMP
"""Generated by tools/sync-shared.sh. Do not edit; do not commit."""

GIT_SHA = "$GIT_SHA"
DIRTY = $DIRTY
STAMPED_AT = "$STAMPED_AT"
STAMP

synced=0
shopt -s nullglob
# Same glob and the same _/. skip rule as infra/locals.tf:23-26, so discovery here
# can never drift from discovery there.
for req in "$ROOT"/backend/*/requirements.txt; do
    svc_dir="$(dirname "$req")"
    svc="$(basename "$svc_dir")"
    case "$svc" in _*|.*) continue ;; esac

    # start-dev.sh counted services by function.py while Terraform discovers by
    # requirements.txt. We no longer use start-dev.sh, but a service without
    # function.py still deploys a Lambda whose handler cannot be imported.
    [ -f "$svc_dir/function.py" ] || echo "  WARN: $svc has requirements.txt but no function.py"

    # The zip patterns in infra/locals.tf:59 are anchored regexes, so they exclude
    # only TOP-LEVEL __pycache__. Nested ones ship, and Python prefers a matching
    # .pyc over source -- so deployed behaviour can diverge from deployed source.
    find "$svc_dir" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

    excludes=(--exclude '__pycache__/' --exclude '*.pyc' --exclude '.pytest_cache/')
    if [ "$svc" != "auth" ]; then
        for item in "${AUTH_ONLY[@]}"; do excludes+=(--exclude "$item"); done
    fi

    # --delete is load-bearing: without it a module deleted from _shared lingers in
    # every copy and keeps satisfying imports, so you ship code that only works
    # because of a stale artifact.
    rsync -a --delete "${excludes[@]}" "$SRC/" "$svc_dir/acme_core/"
    echo "  synced acme_core -> backend/$svc/acme_core  (${GIT_SHA}$([ "$DIRTY" = True ] && echo '-dirty'))"
    synced=$((synced + 1))
done
shopt -u nullglob

[ "$synced" -gt 0 ] || echo "  no services found under backend/ (nothing to sync)"
