"""Schema shape, asserted against the compiled DDL rather than a live database.

These run in the unit tier because they need no connection: SQLAlchemy can
compile the PostgreSQL DDL offline. Behaviour that only a real server can show
-- that a unique constraint actually rejects a duplicate -- is covered by the
integration tier.
"""

from __future__ import annotations

import pytest
from sqlalchemy import CheckConstraint, UniqueConstraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from acme_core.models import EXPECTED_TABLES, Base
from acme_core.models.enums import (
    EscalationStatus,
    IncidentStatus,
    NoteVisibility,
    Priority,
    Role,
)

pytestmark = pytest.mark.unit

TABLES = Base.metadata.tables


def ddl(table_name: str) -> str:
    """Compile a table's PostgreSQL CREATE statement."""
    return str(CreateTable(TABLES[table_name]).compile(dialect=postgresql.dialect()))


class TestMetadataCompleteness:
    def test_every_expected_table_is_registered(self) -> None:
        """A model module nothing imports is invisible to Alembic autogenerate."""
        assert set(TABLES) == set(EXPECTED_TABLES)

    def test_twelve_tables(self) -> None:
        assert len(TABLES) == 12

    @pytest.mark.parametrize("name", sorted(EXPECTED_TABLES))
    def test_every_table_compiles_for_postgresql(self, name: str) -> None:
        assert ddl(name).startswith("\nCREATE TABLE")


class TestNamingConvention:
    """Explicit constraint names keep Alembic downgrades workable.

    A constraint the database named itself cannot be reliably dropped by an
    autogenerated downgrade.
    """

    def test_primary_keys_are_named(self) -> None:
        assert TABLES["users"].primary_key.name == "pk_users"

    def test_foreign_keys_are_named(self) -> None:
        names = {fk.constraint.name for fk in TABLES["incidents"].foreign_keys}
        assert "fk_incidents_reporter_id_users" in names

    def test_unique_constraints_are_named(self) -> None:
        names = {
            c.name for c in TABLES["floors"].constraints if isinstance(c, UniqueConstraint)
        }
        assert "uq_floors_building_id_level" in names


class TestTimestamps:
    @pytest.mark.parametrize("name", sorted(EXPECTED_TABLES))
    def test_no_naive_timestamps_anywhere(self, name: str) -> None:
        """Mixing naive and aware timestamps makes SLA arithmetic silently wrong."""
        assert "WITHOUT TIME ZONE" not in ddl(name)

    def test_incidents_carry_the_four_stamps(self) -> None:
        """Denormalised so SLA reporting is a GROUP BY, not a window function."""
        columns = set(TABLES["incidents"].columns.keys())
        assert {"acknowledged_at", "assigned_at", "resolved_at", "closed_at"} <= columns

    @pytest.mark.parametrize(
        "column", ["acknowledged_at", "assigned_at", "resolved_at", "closed_at"]
    )
    def test_stamps_start_null(self, column: str) -> None:
        """A stamp must mean "this happened", so it cannot default to now()."""
        col = TABLES["incidents"].columns[column]
        assert col.nullable is True
        assert col.server_default is None


class TestEnumConstraints:
    @pytest.mark.parametrize(
        ("table", "enum_cls"),
        [
            ("users", Role),
            ("incidents", IncidentStatus),
            ("incidents", Priority),
            ("incident_notes", NoteVisibility),
            ("escalation_requests", EscalationStatus),
        ],
        ids=lambda v: getattr(v, "__name__", str(v)),
    )
    def test_every_member_appears_in_a_check(self, table: str, enum_cls: type) -> None:
        """create_constraint defaults to False; without it this is a free-text column."""
        statement = ddl(table)
        for member in enum_cls:
            assert f"'{member.value}'" in statement

    def test_checks_are_actually_emitted(self) -> None:
        checks = [
            c for c in TABLES["incidents"].constraints if isinstance(c, CheckConstraint)
        ]
        assert len(checks) >= 2

    def test_values_are_stored_not_names(self) -> None:
        """Rows must read naturally in psql: 'Facility Admin', not 'FACILITY_ADMIN'."""
        statement = ddl("users")
        assert "'Facility Admin'" in statement
        assert "FACILITY_ADMIN" not in statement


class TestLocationRules:
    def test_building_is_required(self) -> None:
        """Every incident happens somewhere."""
        assert TABLES["incidents"].columns["building_id"].nullable is False

    @pytest.mark.parametrize("column", ["floor_id", "seat_id"])
    def test_floor_and_seat_are_optional(self, column: str) -> None:
        """A lobby has no seat; a lift has no floor."""
        assert TABLES["incidents"].columns[column].nullable is True

    def test_floor_is_unique_per_building_level(self) -> None:
        cols = {
            tuple(sorted(c.columns.keys()))
            for c in TABLES["floors"].constraints
            if isinstance(c, UniqueConstraint)
        }
        assert ("building_id", "level") in cols

    def test_seat_is_unique_per_floor_code(self) -> None:
        cols = {
            tuple(sorted(c.columns.keys()))
            for c in TABLES["seats"].constraints
            if isinstance(c, UniqueConstraint)
        }
        assert ("code", "floor_id") in cols


class TestReferentialPolicy:
    def _ondelete(self, table: str, column: str) -> str | None:
        for fk in TABLES[table].foreign_keys:
            if fk.parent.name == column:
                return fk.ondelete
        raise AssertionError(f"no foreign key on {table}.{column}")

    def test_reporter_cannot_be_deleted_away(self) -> None:
        """RESTRICT, not CASCADE: deleting a user must not erase incident history."""
        assert self._ondelete("incidents", "reporter_id") == "RESTRICT"

    def test_assignee_is_nulled_not_cascaded(self) -> None:
        """An engineer leaving must not delete the work they were assigned."""
        assert self._ondelete("incidents", "assignee_id") == "SET NULL"

    @pytest.mark.parametrize(
        ("table", "column"),
        [
            ("incident_notes", "incident_id"),
            ("incident_status_history", "incident_id"),
            ("escalation_requests", "incident_id"),
            ("floors", "building_id"),
            ("seats", "floor_id"),
        ],
    )
    def test_children_cascade_with_their_parent(self, table: str, column: str) -> None:
        assert self._ondelete(table, column) == "CASCADE"

    def test_building_deletion_is_restricted(self) -> None:
        """Deleting a building with incidents must be a 409, not silent data loss."""
        assert self._ondelete("incidents", "building_id") == "RESTRICT"


class TestScopingSupport:
    @pytest.mark.parametrize("column", ["reporter_id", "assignee_id"])
    def test_scoped_columns_are_indexed(self, column: str) -> None:
        """Row-level scoping filters on these on every list query."""
        indexed = {tuple(i.columns.keys())[0] for i in TABLES["incidents"].indexes}
        assert column in indexed

    def test_refresh_token_family_is_indexed(self) -> None:
        """Reuse detection revokes a whole family, which reads every row for it."""
        indexed = {tuple(i.columns.keys())[0] for i in TABLES["refresh_tokens"].indexes}
        assert "family_id" in indexed


class TestCredentialHandling:
    def test_refresh_tokens_store_only_a_hash(self) -> None:
        """A database disclosure must not yield usable credentials."""
        columns = set(TABLES["refresh_tokens"].columns.keys())
        assert "token_hash" in columns
        assert "token" not in columns

    def test_token_hash_is_unique(self) -> None:
        assert TABLES["refresh_tokens"].columns["token_hash"].unique is True

    def test_users_store_only_a_hash(self) -> None:
        columns = set(TABLES["users"].columns.keys())
        assert "password_hash" in columns
        assert "password" not in columns

    def test_email_is_unique(self) -> None:
        assert TABLES["users"].columns["email"].unique is True

    def test_engineer_profile_is_one_to_one(self) -> None:
        assert TABLES["engineer_profiles"].columns["user_id"].unique is True


class TestRevocationSupport:
    def test_users_carry_a_session_cutoff(self) -> None:
        """Lets a role change take effect immediately, not in up to 30 minutes."""
        assert "sessions_valid_from" in TABLES["users"].columns

    def test_users_carry_lockout_state(self) -> None:
        columns = set(TABLES["users"].columns.keys())
        assert {"failed_login_count", "locked_until"} <= columns

    def test_users_are_soft_deletable(self) -> None:
        assert "is_active" in TABLES["users"].columns

    def test_refresh_tokens_are_revocable(self) -> None:
        assert "revoked_at" in TABLES["refresh_tokens"].columns


class TestAppSecrets:
    def test_table_exists(self) -> None:
        """Carrier for the JWT signing key; no Lambda env var can be added."""
        assert "app_secrets" in TABLES

    def test_name_is_the_primary_key(self) -> None:
        """Makes INSERT ... ON CONFLICT DO NOTHING the race-safe write."""
        assert list(TABLES["app_secrets"].primary_key.columns.keys()) == ["name"]


class TestRepresentations:
    """Every model's repr, because a repr reaches logs and tracebacks."""

    @staticmethod
    def _instances() -> dict[str, object]:
        from acme_core.models import (
            AppSecret,
            Building,
            Category,
            EngineerProfile,
            EscalationRequest,
            Floor,
            Incident,
            IncidentNote,
            IncidentStatusHistory,
            RefreshToken,
            Seat,
            User,
        )

        return {
            "User": User(
                email="a@acme.inc", full_name="A", password_hash="$2b$12$topsecrethash"
            ),
            "EngineerProfile": EngineerProfile(specialty="HVAC"),
            "RefreshToken": RefreshToken(token_hash="topsecrethash"),
            "AppSecret": AppSecret(name="jwt", value="topsecretvalue"),
            "Building": Building(code="HQ", name="Headquarters"),
            "Floor": Floor(level=3),
            "Seat": Seat(code="3A-12"),
            "Category": Category(name="HVAC"),
            "Incident": Incident(title="No heating"),
            "IncidentNote": IncidentNote(body="looking into it"),
            "IncidentStatusHistory": IncidentStatusHistory(),
            "EscalationRequest": EscalationRequest(reason="urgent"),
        }

    @pytest.mark.parametrize("name", sorted(_instances.__func__()))
    def test_repr_is_readable(self, name: str) -> None:
        text = repr(self._instances()[name])
        assert text.startswith("<") and text.endswith(">")

    @pytest.mark.parametrize("name", sorted(_instances.__func__()))
    def test_repr_leaks_no_credential(self, name: str) -> None:
        """bandit scans for exactly this, and a traceback carries it to CloudWatch."""
        assert "topsecret" not in repr(self._instances()[name])
